### ISSUE TITLE
presence and absence are switched

### ISSUE THREAD

**Issue by f0nt4** [gchenuet/nest-datagraph#10]
Nest hasn't been set to away at all.
Those 11 hours should be Presence hours.
http://i.imgur.com/SwrdS6W.png

**Comment by bkonings** [comment]
Same as issue https://github.com/gchenuet/nest-datagraph/issues/5
I'll dig around later, think this can be closed.

**Comment by gchenuet** [comment]
Hi,

I'm currently working on this problem.
I'll fix the problem and modify the design by percentage instead of hours, for a better comprehension.

Is it ok for you ?

**Comment by f0nt4** [comment]
Awesome. Maybe you can show the hours in a tooltip when you hover over the percentages?

**Comment by gchenuet** [comment]
Hi,

I just pushed a new version with pourcentage and hours  when you hover over the pourcentage.
[More info](https://github.com/gchenuet/nest-datagraph/commit/afa885f2b23bb891bcabc8f148ce7fb45beea744)
