### ISSUE TITLE
login form

### ISSUE THREAD

**Issue by Crypt0night** [gchenuet/nest-datagraph#11]
Is it possible to create a login form so you need to enter username/password before you see the nest data?

**Comment by gchenuet** [comment]
Hi @Crypt0night,

Add a .htacess file may be a viable solution for you ? 

Originally, as Nest Datagraph shows only data and no actions on devices (Thermostat, Protect, etc.), I choose to release it without login form.

Let me know if the solution fit your requirements :wink:
