### ISSUE TITLE
Add more weather info

### ISSUE THREAD

**Issue by bkonings** [gchenuet/nest-datagraph#13]
Hi,

I've updated my own version to store more weather info.
With that data I now also added some weather icons to the graph with an overlay (work in progress) (see below)

<img width="1159" alt="schermafbeelding 2017-01-19 om 09 17 17" src="https://cloud.githubusercontent.com/assets/2129013/22098733/364f032e-de28-11e6-99b7-b1356dd6ebe9.png"> (note I use curveType: 'function' for a curved line)

I was wondering how to best add these changes to the database, for new installs there is no issue but for upgrades people don't want to lose data.

Regards,

Bas

(i was thinking of making it so that the weather icon is only shown when weather actually changes, but I need to figure out how to handle proper alignment)

**Comment by gchenuet** [comment]
Hi @bkonings,

Great idea to add weather information above graphs !

Weather informations are from OpenWeatherMap ?
We can create a MySQL update script easily to modify the DB schema if you want.

Feel free to open a pull request about this enhancement.

Thanks
Guillaume

**Comment by bkonings** [comment]
Hi,

Yes I just expanded the weatherdata you where already acquiring.
I'll make a pull request

Regards,

Bas
