### ISSUE TITLE
Docker version

### ISSUE THREAD

**Issue by vidia** [gchenuet/nest-datagraph#16]
Do you have any plans/interest in making/distributing a Docker container for this?

**Comment by gchenuet** [comment]
Hi @vidia,

Yes, I can build a Dockerfile or Docker Compose stack if you're looking for !

Guillaume

**Comment by jery19** [comment]
Hi, I saw your project and it look awesome.  I am also looking into deploying it as a docker container.  Is this still into works ?  Regards.

**Comment by gchenuet** [comment]
Hi @vidia, @jery19,

I pushed a Docker version with Docker Compose.
Can you test it and re-open this issue if you find bugs please ?

Thanks,
Guillaume
