### ISSUE TITLE
Cooling Stats

### ISSUE THREAD

**Issue by lozzd** [gchenuet/nest-datagraph#17]
Hi!
Love the graphs. My nest functions only in off or cooling mode, no heating. Have you any plans for adding cooling status on the energy tab? I see right now it's heating oriented. 
Thanks!

**Comment by gchenuet** [comment]
Hi @lozzd, 

Thanks :)
I built the dasboard with an European Thermostat and Cooling feature is disable. 
But I can use the dev tools to add Cooling features.

**Comment by gchenuet** [comment]
I haven't time (and Nest Thermostat) to maintain this project.
Feel free to open a PR to add it :)

Thanks.
