### ISSUE TITLE
Home and away stats still swapped on energy page

### ISSUE THREAD

**Issue by ryan-jacobs** [gchenuet/nest-datagraph#18]
This looks like a continuation of [#5](https://github.com/gchenuet/nest-datagraph/issues/5) and [#10](https://github.com/gchenuet/nest-datagraph/issues/10). On the energy page the at home and away percentages are swapped and the same labels appear to be mismatches on the Presence History graph.

**Comment by gchenuet** [comment]
Thanks for the PR.
