### ISSUE TITLE
Split backend settings in seperate gitignored file

### ISSUE THREAD

**Issue by ryan-jacobs** [gchenuet/nest-datagraph#20]
Managing changes and general VC would be a bit easier if _all_ settings/secrets were split-out into independent files that could be ignored by git. This is already done by the php frontend (ini file), but is not done by the python polling script.

**Comment by gchenuet** [comment]
Hi @ryan-jacobs,

Thanks for your issues and your PR.

I refactored some parts of the code with the last commit and I used some parts of your PR to only use  one config file for backend and frontend.

Thanks !
