### ISSUE TITLE
OpenWeatherMap City

### ISSUE THREAD

**Issue by druw900** [gchenuet/nest-datagraph#27]
The owm_city variable doesn't seem very accurate. Can the code be modified to accept a city ID instead?

**Comment by gchenuet** [comment]
Hi @druw900,

I'll change the owm method to use ID instead of city value.

Thanks,
Guillaume

**Comment by druw900** [comment]
Thanks for the update. I think there is a small issue with the weather_at_place function. When I run the poller.py script I am getting 'id' must be an int. Any ideas?

**Comment by druw900** [comment]
I was able to fix the issue by updating line 77 of poller.py to this...

        observation = owm.weather_at_id(int(c['owm']['owm_city_id']))

**Comment by gchenuet** [comment]
Hi @druw900,

No need to modify the the `poller.py` file.
You to configure the city ID with simple quote (`'`) in the ini file.

I'll change the documentation to prevent this error.

Thanks,
Guillaume

**Comment by Cibico99** [comment]
Just ran your code, and needed to add the int() formatter on the 'owm_city_id' as well. Tried simple quotes and double, still saw as unicode by python using type() on the variable.
