### ISSUE TITLE
Does not handle database or Nest passwords containing '!'

### ISSUE THREAD

**Issue by commiebobdole** [gchenuet/nest-datagraph#30]
The application does not work if either the MySQL password or the Nest account password configured in settings.ini contains an exclamation point (!). I was able to work around this by changing both of the passwords so that they did not include an exclamation point.
 
Interestingly, enclosing the offending password in single quotes enables the poller script to work, but breaks the site. The reverse happens when they are not enclosed in single quotes.

Error from the poller is: 
```
HTTP Error 400: Bad Request"
```
Error from the nginx error log for the site is:
```
[error] 2067#0: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  syntax error, unexpected '!' in ../conf/settings.ini on line 23
 in /opt/nest-datagraph/frontend/php/getDayHum.php on line 2
PHP message: PHP Notice:  date_default_timezone_set(): Timezone ID '' is invalid in /opt/nest-datagraph/frontend/php/getDayHum.php on line 3
PHP message: PHP Warning:  mysqli_connect(): (28000/1045): Access denied for user 'www-data'@'localhost' (using password: NO) in /opt/nest-datagraph/frontend/php/getDayHum.php on line 5
PHP message: PHP Warning:  mysqli_error() expects parameter 1 to be mysqli, boolean given in /opt/nest-datagraph/frontend/php/getDayHum.php on line 6" while reading response header from upstream, client: 10.42.42.104, server: nest.domain.local, request: "GET /php/getDayHum.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "nest.domain.local", referrer: "http://nest.domain.local/"
```

**Comment by gchenuet** [comment]
I haven't time to maintain this project right now.
Could you please open a PR to fix it ?

Thanks :)
