### ISSUE TITLE
Nest-datagraph on Synology NAS : SSL error

### ISSUE THREAD

**Issue by sjirkboon** [gchenuet/nest-datagraph#31]
I am trying to get nest-datagraph running on a synology NAS, the front end works immediately out of the box,  but with the backend python script I get an SSL certificate error:

sjirk@boonshare:/volume1/web/nest/backend$ /usr/local/python/bin/python poller.py
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>

the python version is:
Python 2.7.14 (default, May 28 2018, 14:46:53)
[GCC 4.6.3] on linux2

is there a solution ?

**Comment by gchenuet** [comment]
Closing due to the delay.
Feel free to re-open it if needed.
