### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by seerdekens** [gchenuet/nest-datagraph#32]
Hi,
When building the DockerFile it fails eventually with the following error:

`Step 8/18 : ADD setup/nginx/nest-datagraph.conf /etc/nginx/sites-available/default.conf
ADD failed: stat /var/lib/docker/tmp/docker-builder059889255/setup/nginx/nest-datagraph.conf: no such file or directory`

Any idea?   I'm using Docker on Mac.
Thanks
Steven

**Comment by seerdekens** [comment]
Same issue when trying to build on Linux (Ubuntu).
What is the command/parameters you use to build the container ?

**Comment by seerdekens** [comment]
solved, my bad (docker newbie)

**Comment by gchenuet** [comment]
Cool!
