### ISSUE TITLE
Cannot login after switching to Google account

### ISSUE THREAD

**Issue by shaman79** [gchenuet/nest-datagraph#39]
A week ago I tried to login to my Nest account and then I was asked to switch my Nest account to Google account, which I did. From that time I am no longer seeing any data updates. I guess it is because the old login method no longer works. Even if I enter my Google account credentials it returns HTTP 400.

Is there any workaround for it?

**Comment by gchenuet** [comment]
Hi @shaman79,

Yes, Google killed 'Works with Nest' program and Nest APIs when acquiring the company.
So, when you switched to Google account, nest-datagraph stop working.

I haven't time and Nest thermostat yet to work on it but feel free to open a PR if you find a working solution.

Cheers,
Guillaume
