### ISSUE TITLE
more information in database

### ISSUE THREAD

**Issue by f0nt4** [gchenuet/nest-datagraph#9]
What would happen if I would adjust the crontab to every 5 or 10 minutes? Would it be ok?

**Comment by bkonings** [comment]
Hi, I wouldn't recommend doing that. The nest website will probably throttle you in some way and you won't get data/experience issues with the functioning of your nest devices.

I myself changed it to run every 30 minutes, that has a sideeffect of there being more records then expected and every indicator doubling. (you should see max 24 heating hours but now I see it go up to 48). So the source should probably be updated to account for the script frequency somehow.

**Comment by gchenuet** [comment]
Initially, I wrote the code to fetch informations each hour.
It should be a good idea to enhance the code and accept a lower refresh.
